### PR TITLE
Fix API request sidebar

### LINKED ISSUE #105: API Playground has the lexicon name omitted
When going into the API reference pages, the API playground omits the lexicon name. To be more specific, instead of seeing (for example) `https://bsky.social/xrpc/app.bsky.feed.getPostThread`, you instead see `https://bsky.social/xrpc`.

Below is a video showcasing this issue: 

https://github.com/bluesky-social/bsky-docs/assets/894736/834e66b5-6bf2-4c38-ad66-202453050c8d

Because of this, attempting to test any APIs would lead to 404 errors.

(My apologies for the weird lines in the video: I'm not too sure why it's doing that.)

### LINKED ISSUE #137: code/API example sidebars (right column) does not update with actual API endpoint info
The curl, python, etc code examples on the right are somehow not updated with the actual endpoint being viewed. The URL is always just a base URL (doesn't include the path), the requests are always GET (even for POST endpoints), and no body or query params are included.

I spent an hour or two poking around and can't figure out why this isn't happening. There are just a ton of layers of abstractions/plugins/packages and i'm not familiar with MDX/React to debug this myself.

### PR DESCRIPTION
**Pull request by tom-sherman**
The openapi codegen was generating invalid openapi specs. Paths should start with a `/`.

- Closes #105
- Closes #137

### CODE REVIEW

File: atproto-openapi-types/main.ts [hunk 1]
```diff
@@ -101,15 +101,15 @@ const api: OpenAPIV3_1.Document = {
...
       description: "Bluesky AppView (Public, No Auth)",
     },
     {
-      url: "https://pds.example.org/xrpc/",
+      url: "https://pds.example.org/xrpc",
       description: "Example atproto PDS (Authenticated)",
     },
     {
-      url: "https://bsky.network/xrpc/",
+      url: "https://bsky.network/xrpc",
```
Comment (tom-sherman) [inline atproto-openapi-types/main.ts:112]: This change fixes a display bug where now that all of the paths have the `/` at the beginning, the oai explorer lib was showing the full URL with double `//` in the `MethodEndpoint` component

image

**Review by ericvolp12 — APPROVED** [review]
LGTM, thanks for the contribution!
